header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: "Simon Emms <simon@simonemms.com>"
  paths-ignore:
    - dist
    - tmp
    - LICENSE
    - .*
    - "go.*"
    - "**/*.{json,md,yml,yaml}"
    - "**/.gitkeep"
    - "**/*.svelte"
  comment: on-failure

dependency:
  files:
    - package.json # If this is a npm project.
